name: MCP CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure uv
        uses: astral-sh/setup-uv@v1
        with:
          packages: ruff, pytest

      - name: Install project dependencies
        run: uv sync

      - name: Lint with ruff
        run: |
          uv run ruff check .

      - name: Test with pytest
        run: |
          uv run pytest tests/test_client.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
